List countryName = [
  "Afghanistan"
      'Albania'
      'Algeria'
      'American Samoa'
      'Andorra'
      'Angola'
      'Anguilla'
      'Antarctica'
      'Antigua and Barbuda'
      'Argentina'
      'Armenia'
      'Aruba'
      'Australia'
      'Austria'
      'Azerbaijan'
      'Bahamas (the)'
      'Bahrain'
      'Bangladesh'
      'Barbados'
      'Belarus'
      'Belgium'
      'Belize'
      'Benin'
      'Bermuda'
      'Bhutan'
      'Bolivia (Plurinational State of)'
      'Bonaire, Sint Eustatius and Saba'
      'Bosnia and Herzegovina'
      'Botswana'
      'Bouvet Island'
      'Brazil'
      'British Indian'
      'Brunei Darussalam'
      'Bulgaria'
      'Burkina Faso'
      'Burundi'
      'Cabo Verde'
      'Cambodia'
      'Cameroon'
      'Canada'
      'Cayman Islands'
      'Central African Republic'
      'Chad'
      'Chile'
      'China'
      'Christmas Island'
      'Cocos'
      'Colombia'
      'Comoros'
      'Congo'
      'Congo '
      'Cook Islands'
      'Costa Rica'
      'Croatia'
      'Cuba'
      'Curaçao'
      'Cyprus'
      'Czechia'
      'Côte d\'Ivoire'
      'Denmark'
      'Djibouti'
      'Dominica'
      'Dominican Republic'
      'Ecuador'
      'Egypt'
      'El Salvador'
      'Equatorial Guinea'
      'Eritrea'
      'Estonia'
      'Eswatini'
      'Ethiopia'
      'Falkland Islands'
      'Faroe Islands'
      'Fiji'
      'Finland'
      'France'
      'French Guiana'
      'French Polynesia'
      'French '
      'Gabon'
      'Gambia'
      'Georgia'
      'Germany'
      'Ghana'
      'Gibraltar'
      'Greece'
      'Greenland'
      'Grenada'
      'Guadeloupe'
      'Guam'
      'Guatemala'
      'Guernsey'
      'Guinea'
      'Guinea-Bissau'
      'Guyana'
      'Haiti'
      'Heard Island'
      'Holy See'
      'Honduras'
      'Hong Kong'
      'Hungary'
      'Iceland'
      'India'
      'Indonesia'
      'Iran'
      'Iraq'
      'Ireland'
      'Isle of Man'
      'Israel'
      'Italy'
      'Jamaica'
      'Japan'
      'Jersey'
      'Jordan'
      'Kazakhstan'
      'Kenya'
      'Kiribati'
      'Korea '
      'Korea '
      'Kuwait'
      'Kyrgyzstan'
      'Lao People'
      'Latvia'
      'Lebanon'
      'Lesotho'
      'Liberia'
      'Libya'
      'Liechtenstein'
      'Lithuania'
      'Luxembourg'
      'Macao'
      'Madagascar'
      'Malawi'
      'Malaysia'
      'Maldives'
      'Mali'
      'Malta'
      'Marshall Islands'
      'Martinique'
      'Mauritania'
      'Mauritius'
      'Mayotte'
      'Mexico'
      'Micronesia'
      'Moldova'
      'Monaco'
      'Mongolia'
      'Montenegro'
      'Montserrat'
      'Morocco'
      'Mozambique'
      'Myanmar'
      'Namibia'
      'Nauru'
      'Nepal'
      'Netherlands'
      'New Caledonia'
      'New Zealand'
      'Nicaragua'
      'Niger'
      'Nigeria'
      'Niue'
      'Norfolk Island'
      'Northern Mariana'
      'Norway'
      'Oman'
      'Pakistan'
      'Palau'
      'Palestine'
      'Panama'
      'Papua New Guinea'
      'Paraguay'
      'Peru'
      'Philippines'
      'Pitcairn'
      'Poland'
      'Portugal'
      'Puerto Rico'
      'Qatar'
      'North Macedonia'
      'Romania'
      'Russian Federation'
      'Rwanda'
      'Réunion'
      'Saint Barthélemy'
      'Saint Helena'
      'Saint Kitts'
      'Saint Lucia'
      'Saint Martin'
      'Saint Pierre '
      'Saint Vincent '
      'Samoa'
      'San Marino'
      'Sao Tome '
      'Saudi Arabia'
      'Senegal'
      'Serbia'
      'Seychelles'
      'Sierra Leone'
      'Singapore'
      'Sint Maarten'
      'Slovakia'
      'Slovenia'
      'Solomon Islands'
      'Somalia'
      'South Africa'
      'South Georgia'
      'South Sudan'
      'Spain'
      'Sri Lanka'
      'Sudan'
      'Suriname'
      'Svalbard and Jan Mayen'
      'Sweden'
      'Switzerland'
      'Syrian Arab Republic'
      'Taiwan '
      'Tajikistan'
      'Tanzania'
      'Thailand'
      'Timor-Leste'
      'Togo'
      'Tokelau'
      'Tonga'
      'Trinidad and Tobago'
      'Tunisia'
      'Turkey'
      'Turkmenistan'
      'Turks and Caicos'
      'Tuvalu'
      'Uganda'
      'Ukraine'
      'United Arab Emirates'
      'United Kingdom '
      'United States'
      'United States of America (the)'
      'Uruguay'
      'Uzbekistan'
      'Vanuatu'
      'Venezuela (Bolivarian Republic of)'
      'Viet Nam'
      'Virgin Islands (British)'
      'Virgin Islands (U.S.)'
      'Wallis and Futuna'
      'Western Sahara'
      'Yemen'
      'Zambia'
      'Zimbabwe'
      'Åland Islands'
];
